dist: trusty
sudo: false
language: erlang 

script:
  - wget -O- https://tmvg.home.xs4all.nl/travis/debootstrap.sh | sh -

branches:
  except:
    - /^debian\/\d/

git:
  depth: 3
  lfs_skip_smudge: true

addons:
  apt:
    packages:
    - ca-certificates
    - debootstrap
