sudo: required
language: generic

services:
  - docker

script:
  - wget -O- https://tmvg.home.xs4all.nl/travis/script.sh | sh -

branches:
  except:
    - /^debian\/\d/

git:
  depth: 3
  lfs_skip_smudge: true
